// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4SFNnxiyWKzpYZxVXfJ49mhovLvr36A',
    appId: '1:251749240945:web:08e1e0b0712cfe16ec4bd0',
    messagingSenderId: '251749240945',
    projectId: 'semester-projekt-38bc1',
    authDomain: 'semester-projekt-38bc1.firebaseapp.com',
    databaseURL: 'https://semester-projekt-38bc1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'semester-projekt-38bc1.firebasestorage.app',
    measurementId: 'G-PQ7XRT1ZL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtBNDYbrhR_3oJrGko4nlifnXxdzOLTCY',
    appId: '1:251749240945:android:89f0120db0eb5486ec4bd0',
    messagingSenderId: '251749240945',
    projectId: 'semester-projekt-38bc1',
    databaseURL: 'https://semester-projekt-38bc1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'semester-projekt-38bc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByXh0shbounE5yoAVRkRY5hlzr9nP6H88',
    appId: '1:251749240945:ios:358222429324e641ec4bd0',
    messagingSenderId: '251749240945',
    projectId: 'semester-projekt-38bc1',
    databaseURL: 'https://semester-projekt-38bc1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'semester-projekt-38bc1.firebasestorage.app',
    iosBundleId: 'com.example.raman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByXh0shbounE5yoAVRkRY5hlzr9nP6H88',
    appId: '1:251749240945:ios:358222429324e641ec4bd0',
    messagingSenderId: '251749240945',
    projectId: 'semester-projekt-38bc1',
    databaseURL: 'https://semester-projekt-38bc1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'semester-projekt-38bc1.firebasestorage.app',
    iosBundleId: 'com.example.raman',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB4SFNnxiyWKzpYZxVXfJ49mhovLvr36A',
    appId: '1:251749240945:web:6afdf50c725270c2ec4bd0',
    messagingSenderId: '251749240945',
    projectId: 'semester-projekt-38bc1',
    authDomain: 'semester-projekt-38bc1.firebaseapp.com',
    databaseURL: 'https://semester-projekt-38bc1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'semester-projekt-38bc1.firebasestorage.app',
    measurementId: 'G-HHLFCXV8XN',
  );
}
